format = """\
[╭──](240) \
$env_var\
$all \
$fill\
$cmd_duration $jobs $time $line_break\
[╰─](240)$character"""

add_newline = true

[character]
error_symbol   = "[→](red)"
success_symbol = "[→](240)"

[fill]
symbol = " "

[directory]
home_symbol       = "󰋜 ~"
read_only         = " "
style             = "cyan"
truncate_to_repo  = false
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
style  = "green"
symbol = " "

[git_status]
ahead    = "⇡${count}"
behind   = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format   = '([\[$all_status$ahead_behind\]]($style) )'
style    = "green"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style  = "yellow"

[time]
disabled    = false
format      = "[$time]($style)"
style       = "bold white"
time_format = "%I:%M %p"

[aws]
disabled = true

[gcloud]
disabled = true
