#!/bin/sh
# Xsetup - run as root before the login dialog appears

if [ -e /sbin/prime-offload ]; then
    echo running NVIDIA Prime setup /sbin/prime-offload
    /sbin/prime-offload
fi

xrandr --output DP-4   --mode 1920x1080 --pos 1920x0    --rate 240 --primary
xrandr --output DP-2   --mode 1920x1080 --pos 0x0       --rate 60
xrandr --output HDMI-0 --mode 1920x1080 --pos 3840x112  --rate 60
